#ifndef AUDIO_PROCESS_H
#define AUDIO_PROCESS_H

#include <stdint.h>

#include "pulseaudio.h"


#define AUDIO_PROCESS_SAMPLE_RATE    44100
#define AUDIO_PROCESS_TARGET_LATENCY 2  // In msec
#define AUDIO_PROCESS_FFTS_PER_SEC   DIV_ROUND(1000, AUDIO_PROCESS_TARGET_LATENCY)
#define AUDIO_PROCESS_QUEUE_LEN      10

#define PULSEAUDIO_NBR_CHANNELS      2
#define PULSEAUDIO_FORMAT            PA_SAMPLE_S16LE
#define PULSEAUDIO_SAMPLE_TYPE       int16_t
#define PULSEAUDIO_SAMPLE_BYTES      2
#define PULSEAUDIO_CHUNK_BYTES       (PULSEAUDIO_NBR_CHANNELS * PULSEAUDIO_SAMPLE_BYTES)
#define PULSEAUDIO_BUFSIZE           DIV_ROUND((AUDIO_PROCESS_TARGET_LATENCY * AUDIO_PROCESS_SAMPLE_RATE * PULSEAUDIO_CHUNK_BYTES), 1000)


void audio_process_add_samples(PULSEAUDIO_SAMPLE_TYPE *data_left, PULSEAUDIO_SAMPLE_TYPE *data_right, size_t nbr_channel_samples);
void audio_process_start();


#endif//AUDIO_PROCESS_H
