#ifndef PULSEAUDIO_H
#define PULSEAUDIO_H


#include "util.h"


#define PULSEAUDIO_NBR_CHANNELS      2
#define PULSEAUDIO_FORMAT            PA_SAMPLE_S16LE
#define PULSEAUDIO_SAMPLE_TYPE       int16_t
#define PULSEAUDIO_SAMPLE_BYTES      2
#define PULSEAUDIO_CHUNK_BYTES       (PULSEAUDIO_NBR_CHANNELS * PULSEAUDIO_SAMPLE_BYTES)
#define PULSEAUDIO_BUFSIZE           DIV_ROUND((AUDIO_PROCESS_SAMPLE_RATE * PULSEAUDIO_CHUNK_BYTES * AUDIO_PROCESS_TARGET_LATENCY), 1000)


ret_code pulseaudio_init();


#endif//PULSEAUDIO_H

